-- ============================================
-- Student Track System - Single Consolidated Database Script (All-in-One)
-- Generated by consolidation of setup + migrations
-- ============================================

-- Drop existing database to clear all old data
DROP DATABASE IF EXISTS student_track_system;

-- Create fresh database
CREATE DATABASE student_track_system;
USE student_track_system;

-- ============================================
-- CORE TABLES
-- ============================================

-- Roles table
CREATE TABLE roles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name ENUM('ROLE_HOD', 'ROLE_FACULTY', 'ROLE_STUDENT') NOT NULL UNIQUE,
    INDEX idx_roles_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Users table (with roll_number field)
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(20) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(120) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    roll_number VARCHAR(50) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_users_username (username),
    INDEX idx_users_email (email),
    INDEX idx_users_roll_number (roll_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- User roles mapping
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- TASK MANAGEMENT
-- ============================================
CREATE TABLE tasks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    subject VARCHAR(100) NULL,
    status ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    assigned_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    due_date TIMESTAMP NULL,
    FOREIGN KEY (assigned_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_tasks_assigned_to (assigned_to_id),
    INDEX idx_tasks_assigned_by (assigned_by_id),
    INDEX idx_tasks_status (status),
    INDEX idx_tasks_due_date (due_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE submissions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(2000) NOT NULL,
    task_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_path VARCHAR(500) NULL,
    file_name VARCHAR(255) NULL,
    file_size BIGINT NULL,
    status VARCHAR(20) DEFAULT 'PENDING',
    faculty_remark VARCHAR(1000) NULL,
    marked_complete_at TIMESTAMP NULL,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_submissions_task (task_id),
    INDEX idx_submissions_student (student_id),
    INDEX idx_submissions_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- COMMUNICATION
-- ============================================
CREATE TABLE feedbacks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    content VARCHAR(1000) NOT NULL,
    task_id BIGINT NOT NULL,
    faculty_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (faculty_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_feedbacks_task (task_id),
    INDEX idx_feedbacks_student (student_id),
    INDEX idx_feedbacks_faculty (faculty_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE notes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content VARCHAR(2000) NOT NULL,
    created_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT NULL,
    is_public BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    file_name VARCHAR(255) NULL,
    file_path VARCHAR(500) NULL,
    file_size BIGINT NULL,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_notes_created_by (created_by_id),
    INDEX idx_notes_assigned_to (assigned_to_id),
    INDEX idx_notes_public (is_public)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- ATTENDANCE
-- ============================================
CREATE TABLE attendance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    student_id BIGINT NOT NULL,
    faculty_id BIGINT NOT NULL,
    status ENUM('PRESENT', 'ABSENT', 'LATE', 'EXCUSED') NOT NULL,
    subject VARCHAR(100) NULL,
    remarks VARCHAR(500) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_attendance_per_faculty (date, student_id, faculty_id),
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (faculty_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_attendance_date (date),
    INDEX idx_attendance_student (student_id),
    INDEX idx_attendance_faculty (faculty_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- ASSESSMENTS
-- ============================================
CREATE TABLE quizzes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description VARCHAR(1000) NULL,
    created_by_id BIGINT NOT NULL,
    start_time TIMESTAMP NULL,
    end_time TIMESTAMP NULL,
    total_marks INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_quizzes_created_by (created_by_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE quiz_questions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    quiz_id BIGINT NOT NULL,
    question_text VARCHAR(1000) NOT NULL,
    marks INT NOT NULL DEFAULT 1,
    question_order INT NOT NULL DEFAULT 0,
    FOREIGN KEY (quiz_id) REFERENCES quizzes(id) ON DELETE CASCADE,
    INDEX idx_quiz_questions_quiz (quiz_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE quiz_options (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    question_id BIGINT NOT NULL,
    option_text VARCHAR(500) NOT NULL,
    is_correct BOOLEAN DEFAULT FALSE,
    option_order INT NOT NULL DEFAULT 0,
    FOREIGN KEY (question_id) REFERENCES quiz_questions(id) ON DELETE CASCADE,
    INDEX idx_quiz_options_question (question_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE marks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT NOT NULL,
    faculty_id BIGINT NOT NULL,
    subject VARCHAR(100) NOT NULL,
    assessment_type ENUM('UNIT_TEST_1', 'UNIT_TEST_2', 'SEMESTER_EXAM', 'TASK', 'QUIZ') NOT NULL,
    marks INT NOT NULL,
    max_marks INT NOT NULL,
    remarks VARCHAR(500) NULL,
    date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (faculty_id) REFERENCES users(id) ON DELETE CASCADE,
    INDEX idx_marks_student (student_id),
    INDEX idx_marks_faculty (faculty_id),
    INDEX idx_marks_subject (subject),
    INDEX idx_marks_date (date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================
-- SEED DATA
-- ============================================
INSERT INTO roles (name) VALUES 
('ROLE_HOD'),
('ROLE_FACULTY'),
('ROLE_STUDENT');

INSERT INTO users (username, email, password, full_name, roll_number) VALUES 
('hod', 'hod@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'Head of Department', NULL),
('faculty1', 'faculty1@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'John Faculty', NULL),
('student1', 'student1@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'Alice Student', 'STU001'),
('student2', 'student2@example.com', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', 'Bob Student', 'STU002');

INSERT INTO user_roles (user_id, role_id) VALUES 
(1, 1),
(2, 2),
(3, 3),
(4, 3);

INSERT INTO tasks (title, description, subject, assigned_by_id, assigned_to_id, status, due_date) VALUES 
('Research Project', 'Complete research on machine learning algorithms', 'Computer Science', 2, 3, 'IN_PROGRESS', '2025-11-30 23:59:59'),
('Assignment 1', 'Solve mathematical problems from chapter 5', 'Mathematics', 2, 3, 'PENDING', '2025-11-25 23:59:59'),
('Lab Report', 'Write lab report for chemistry experiment', 'Chemistry', 2, 4, 'COMPLETED', '2025-11-20 23:59:59');

INSERT INTO submissions (content, task_id, student_id, status, faculty_remark, submitted_at, marked_complete_at) VALUES 
('Completed the research on ML algorithms. Attached report.', 1, 3, 'PENDING', NULL, '2025-11-10 10:30:00', NULL),
('Solutions for chapter 5 problems attached.', 2, 3, 'PENDING', NULL, '2025-11-10 14:20:00', NULL),
('Lab report completed with all observations.', 3, 4, 'COMPLETED', 'Excellent work! Well documented.', '2025-11-09 16:45:00', '2025-11-10 09:00:00');

-- SUMMARY
SELECT 'Database setup complete!' AS Status;
SELECT COUNT(*) AS total_users FROM users;
SELECT COUNT(*) AS total_tasks FROM tasks;
SELECT COUNT(*) AS total_submissions FROM submissions;
